### ISSUE TITLE
Add some of your other audits

### ISSUE THREAD

**Issue by jkup** [perfs/audits#3]
I would love to have a centralized repo for perf audits. I know @paulirish and @samccone have done some that I have bookmarked. Mainly:
- [RAIL &amp; user-centric performance](https://docs.google.com/document/d/1jqYyv-3cgGZBJb86qMT-M9YHCh-SpzScJabIvj7FjsE/view)
- [Tumblr perf](https://docs.google.com/document/d/1E2w0UQ4RhId5cMYsDcdcNwsgL0gP_S6SDv27yi1mCEY/edit)

Would it be worthwhile to add those to this repo and  link to them all from the readme?

**Comment by paulirish** [comment]
tumblr was added to the readme at some point

also hello! randomly cleaning up stuff from years ago lol
