### ISSUE TITLE
Make @samccone stop tweetstorming and write posts instead

### ISSUE THREAD

**Issue by sebmck** [perfs/audits#4]

**Comment by jkup** [comment]
lol'd when I saw this (also would love them here for future reference)

**Comment by montogeek** [comment]
Related: https://github.com/perfs/audits/issues/5

**Comment by ritz078** [comment]
@kittens @jkup posts will be great and we will be happy to contribute.

**Comment by sebmck** [comment]
Ping, any update on this issue? No issue triaging to speak of either. Absolutely despicable. This should be given a high priority tag with multiple assignee's.

**Comment by jhermann** [comment]
Hmmm, seems there is actual content hidden somewhere, which is not linked by the 2yo readme, the orga web link, or this project's web link. :confused: 

Any pointers?

**Comment by paulirish** [comment]
fixed by #5 i guess right? okay thanks

<3 u guys
